NUMPY

In [ ]:
import numpy as np
#!pip install numpy

In [ ]:
arr=np.array([10,20,30,40])
print(arr)

[10 20 30 40]

In [ ]:
arr2d=np.array([[2,2,2],
                [3,3,3]])
print(arr2d)

[[2 2 2]
 [3 3 3]]

In [ ]:
arr3d=np.array([[[2,2],[2,2]],
                [[3,3],[3,3]]])
print(arr3d)
print("Dimension of array",arr3d.ndim)
print("Rows and columns",arr3d.shape)
print("Data type ",arr3d.dtype)
print("size",arr.size)

[[[2 2]
  [2 2]]

 [[3 3]
  [3 3]]]
Dimension of array 3
Rows and columns (2, 2, 2)
Data type  int64
size 4

In [ ]:
arr1=np.arange(16)
print(arr1)
arr_reshape=arr1.reshape(4,4)
print(arr_reshape)
print("shape after reshaping 4,4 ",arr_reshape.shape)
print("2nd row 1 element",arr_reshape[1][0])
arr2=np.arange(5,20,2)
print(arr2)
arr3=np.random.randint(1,100,16)
print(arr3)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
shape after reshaping 4,4  (4, 4)
2nd row 1 element 4
[ 5  7  9 11 13 15 17 19]
[75 11 37 87 89  4 11 18 72 17 64 54 61 42 51 94]

In [ ]:
arr1=np.arange(16)
print(arr1)
arr3=np.random.randint(1,100,16)
print(arr3)
print("Addition",arr1+arr3)
print("Subraction",arr1-arr3)
print("Multiplication \n",arr1*arr3)
print("Divison \n",arr1/arr3)
print("square of arr1",np.square(arr1))
print("suareroot of arr1",np.sqrt(arr1))
print("tan of arr1",np.tan(arr2))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[71 80 26 38 83 25 34 82 92 50 24 93 56 89 50 49]
Addition [ 71  81  28  41  87  30  40  89 100  59  34 104  68 102  64  64]
Subraction [-71 -79 -24 -35 -79 -20 -28 -75 -84 -41 -14 -82 -44 -76 -36 -34]
Multiplication
 [   0   80   52  114  332  125  204  574  736  450  240 1023  672 1157
  700  735]
Divison
 [0.         0.0125     0.07692308 0.07894737 0.04819277 0.2
 0.17647059 0.08536585 0.08695652 0.18       0.41666667 0.11827957
 0.21428571 0.14606742 0.28       0.30612245]
square of arr1 [  0   1   4   9  16  25  36  49  64  81 100 121 144 169 196 225]
suareroot of arr1 [0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.         3.16227766 3.31662479
 3.46410162 3.60555128 3.74165739 3.87298335]
tan of arr1 [-3.38051501e+00  8.71447983e-01 -4.52315659e-01 -2.25950846e+02
  4.63021133e-01 -8.55993401e-01  3.49391565e+00  1.51589471e-01]

In [ ]:
ar2=np.arange(5,20,2)
print(arr2)
print("max",arr2.max())
print("sum",arr2.sum())
arr3=np.random.randint(1,100,16)
print(arr3)
print("sort",np.sort(arr3))
print("slicing",arr3[3:5])

[ 5  7  9 11 13 15 17 19]
max 19
sum 96
[66 18 81 49 68 13 95 18 98 59 54 74 88 71 17 89]
sort [13 17 18 18 49 54 59 66 68 71 74 81 88 89 95 98]
slicing [49 68]

In [ ]:
arr4=arr3.reshape(4,4)
arr5=arr1.reshape(4,4)
print(np.matmul(arr4,arr5))

[[1308 1522 1736 1950]
 [1028 1222 1416 1610]
 [1556 1841 2126 2411]
 [1488 1753 2018 2283]]

In [ ]:
#comput the transpose ,determinant, and inverse of a 3x3 matrix.arange 9 elements
arr1 = np.array([[1,2,3],
               [0,1,4],
               [5,6,0]])
print(arr1)
print("Transpose:\n",arr1.T)
print("Determinant:",np.linalg.det(arr1))
print("Inverse:\n",np.linalg.inv(arr1))

[[1 2 3]
 [0 1 4]
 [5 6 0]]
Transpose:
 [[1 0 5]
 [2 1 6]
 [3 4 0]]
Determinant: 0.9999999999999964
Inverse:
 [[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]

In [ ]:
arr1=np.arange(9).reshape(3,3)
print(arr1)
for row in arr1:
 for value in row:
  print(value)
print("one dim array")
arr1d=np.arange(5,20,3)
for element in arr1d:
 print(element)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
0
1
2
3
4
5
6
7
8
one dim array
5
8
11
14
17

PANDAS

In [5]:
#pandas
#1D-series 2D-data frames
import numpy as np
import pandas as pd

In [16]:
marks=pd.Series([89,78,88,97,86,58,67,79],index=["alice","bob","charles","david","a","b","c","d"])
print(marks["alice"])

89

In [17]:
rangeseries=pd.Series(range(1,40,2))
print(rangeseries[-10:])

10    21
11    23
12    25
13    27
14    29
15    31
16    33
17    35
18    37
19    39
dtype: int64

Display Series Information

Given:

marks=pd.series([85,90,78,88,95])

Display:

- Number of elements

- data type

- shape

- index

In [19]:
import pandas as pd
marks=pd.Series([85,90,78,88,95])
print(marks.dtype)
print(marks.size)
print(marks.shape)
print(marks.index)

int64
5
(5,)
RangeIndex(start=0, stop=5, step=1)

Slice a Series

Given:

numbers=pd.Series([10,20,30,40,50,60,70])

Display

- first three elements

- last three elements

- elelments from inde 2 to 5

In [20]:
num=pd.Series([10,20,30,40,50,60,70])
print(num[:3])
print(num[-3:])
print(num[2:6])

0    10
1    20
2    30
dtype: int64
4    50
5    60
6    70
dtype: int64
2    30
3    40
4    50
5    60
dtype: int64

In [21]:
#Data Frame is a dimensional data,consider it as table with rows and columns
data={
    "Name":["Alice","Bob","Charles"],
    "Age":[18,21,19],
    "Marks":[78,88,97]
}
df=pd. DataFrame(data)
print(data)
print("name\n",data["Name"])

{'Name': ['Alice', 'Bob', 'Charles'], 'Age': [18, 21, 19], 'Marks': [78, 88, 97]}
name
 ['Alice', 'Bob', 'Charles']

In [23]:
print(df.tail())
print("Shape",df.shape)
print("name\n",data["Name"])

      Name  Age  Marks
0    Alice   18     78
1      Bob   21     88
2  Charles   19     97
Shape (3, 3)
name
 ['Alice', 'Bob', 'Charles']

In [24]:
#df.info
df.describe()

             Age      Marks
count   3.000000   3.000000
mean   19.333333  87.666667
std     1.527525   9.504385
min    18.000000  78.000000
25%    18.500000  83.000000
50%    19.000000  88.000000
75%    20.000000  92.500000
max    21.000000  97.000000

In [29]:
#columns
print("column Age \n",df["Age"])
print("row \n",df.loc[0])
print("Index location\n",df.iloc[0])

column Age
 0    18
1    21
2    19
Name: Age, dtype: int64
row
 Name     Alice
Age         18
Marks       78
Name: 0, dtype: object
Index location
 Name     Alice
Age         18
Marks       78
Name: 0, dtype: object

In [30]:
df.iloc[:2]

    Name  Age  Marks
0  Alice   18     78
1    Bob   21     88

In [31]:
#Adding a column
df["city"]=["Delhi","Mumbai","Calcutta"]
print(df.head())
df.drop("Marks",axis=1,inplace=True)
print(df.head)

      Name  Age  Marks      city
0    Alice   18     78     Delhi
1      Bob   21     88    Mumbai
2  Charles   19     97  Calcutta
<bound method NDFrame.head of       Name  Age      city
0    Alice   18     Delhi
1      Bob   21    Mumbai
2  Charles   19  Calcutta>

In [32]:
data=[["Alice","Bob","Charles"],
      [18,21,19],
      [78,88,97]]
df_list=pd.DataFrame(data,columns=["Name","Age","Marks"])
print(df_list.head())

    Name  Age    Marks
0  Alice  Bob  Charles
1     18   21       19
2     78   88       97

In [35]:
SeriesRandom=pd.Series(np.random.randint(100,999,30))
print(SeriesRandom)

0     440
1     952
2     665
3     106
4     499
5     412
6     571
7     519
8     290
9     909
10    316
11    527
12    535
13    746
14    632
15    342
16    932
17    425
18    957
19    274
20    377
21    698
22    936
23    506
24    772
25    604
26    459
27    101
28    612
29    228
dtype: int64